// <auto-generated />
using Book_Shop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_Shop.Migrations
{
    [DbContext(typeof(BookShopDbContext))]
    [Migration("20250905173026_Update-Author")]
    partial class UpdateAuthor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_Shop.Data.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "George R.R. Martin"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "C.S. Lewis"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Suzanne Collins"
                        });
                });

            modelBuilder.Entity("Book_Shop.Data.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrilogiesId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.HasIndex("TrilogiesId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "Published by Allen & Unwin",
                            GenreId = 1,
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1566425108i/33.jpg",
                            NumberOfPages = 1178,
                            Price = 20,
                            Title = "The Lord of the Rings",
                            TrilogiesId = 1,
                            Year = 1954
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Description = "Published by Allen & Unwin",
                            GenreId = 2,
                            ImageUrl = "https://www.britishbook.ua/upload/resize_cache/iblock/3ae/r816m7e8jmluhoml6zvy2yhloaoa4ya2/340_500_174b5ed2089e1946312e2a80dcd26f146/kniga_the_hobbit.jpg",
                            NumberOfPages = 310,
                            Price = 15,
                            Title = "The Hobbit",
                            TrilogiesId = 1,
                            Year = 1937
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Description = "Published by Allen & Unwin",
                            GenreId = 1,
                            ImageUrl = "https://content2.rozetka.com.ua/goods/images/big/196236109.jpg",
                            NumberOfPages = 365,
                            Price = 25,
                            Title = "The Silmarillion",
                            TrilogiesId = 1,
                            Year = 1977
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Description = "Published by Bloomsbury",
                            GenreId = 1,
                            ImageUrl = "https://m.media-amazon.com/images/I/81q77Q39nEL.jpg",
                            NumberOfPages = 223,
                            Price = 18,
                            Title = "Harry Potter and the Philosopher's Stone",
                            TrilogiesId = 2,
                            Year = 1997
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Description = "Published by Bloomsbury",
                            GenreId = 1,
                            ImageUrl = "https://static.yakaboo.ua/media/catalog/product/9/7/9781408855669.jpg",
                            NumberOfPages = 251,
                            Price = 20,
                            Title = "Harry Potter and the Chamber of Secrets",
                            TrilogiesId = 2,
                            Year = 1998
                        });
                });

            modelBuilder.Entity("Book_Shop.Data.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            GenreName = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            GenreName = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            GenreName = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            GenreName = "Mystery"
                        });
                });

            modelBuilder.Entity("Book_Shop.Data.Entities.Trilogies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameTrilogie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trilogies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameTrilogie = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 2,
                            NameTrilogie = "Harry Potter"
                        },
                        new
                        {
                            Id = 3,
                            NameTrilogie = "A Song of Ice and Fire"
                        },
                        new
                        {
                            Id = 4,
                            NameTrilogie = "The Chronicles of Narnia"
                        },
                        new
                        {
                            Id = 5,
                            NameTrilogie = "The Hunger Games"
                        });
                });

            modelBuilder.Entity("Book_Shop.Data.Entities.Book", b =>
                {
                    b.HasOne("Book_Shop.Data.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Book_Shop.Data.Entities.Genre", "Genres")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Book_Shop.Data.Entities.Trilogies", "Trilogies")
                        .WithMany("Books")
                        .HasForeignKey("TrilogiesId");

                    b.Navigation("Author");

                    b.Navigation("Genres");

                    b.Navigation("Trilogies");
                });

            modelBuilder.Entity("Book_Shop.Data.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Book_Shop.Data.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Book_Shop.Data.Entities.Trilogies", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
